spring:
  application:
    name: demo
  
  redis:
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

redisson:
  config: |
    singleServerConfig:
      address: "redis://localhost:6379"
      timeout: 2000
      retryAttempts: 3
      retryInterval: 1500
    localCacheConfig:
      cacheSize: 1000
      timeToLiveInMillis: 300000
      maxIdleInMillis: 300000
      evictionPolicy: LRU
      syncStrategy: INVALIDATE

logging:
  level:
    com.example.demo: DEBUG
    org.springframework.cache: DEBUG
